refactor: improve vaults and ironbank overview
yearn/yearn-devdocs pull request #155
Opened 2022-02-02 12:26 UTC by MarcoWorms

tackles parts of #150

2022-02-04 19:47 UTC, KurogeWashu approved these changes
lgtm!

2022-02-09 10:58 UTC, saltyfacu commented on docs/getting-started/products/yvaults/overview.md
> +[yVaults](https://yearn.finance/vaults) takes deposits then route it through strategies which seek out the highest yield available in DeFi. [yVaults and Strategies](https://medium.com/iearn/yearn-fin
yVaults take~~s~~

deposits **and** then route ~~it~~ them

Please take another look to improve the redaction. IMO, it's all over the place

2022-02-09 10:58 UTC, saltyfacu commented on docs/getting-started/products/iron-bank/collateral-and-reserve-factor.md
> +The Iron Bank provides a lending service both to users and protocols. For protocols that are whitelisted this can be zero-collateral loans. For users, this will be an overcollateralised loan. Unlike
IB and yVaults are very different things. You can't compare both. IB is a lending market

2022-02-09 10:59 UTC, saltyfacu requested changes
please check the comments

2022-04-15 14:55 UTC, saltyfacu commented
IB is a standalone product and should not be in our dos anymore. Closing this

2022-04-15 14:55 UTC, closed without merging