add vault factories
yearn/yearn-devdocs pull request #299
Opened 2023-01-03 18:20 UTC by MarcoWorms

2023-01-03 22:45 UTC, DarkGhost7 requested changes

2023-01-03 22:45 UTC, DarkGhost7 commented on docs/getting-started/products/yvaults/vault-factory.md
> +2. Call `createNewVaultsAndStrategies()` to create a new permisionless vault for.
permisionless > permissionless

2023-01-03 22:45 UTC, DarkGhost7 commented on docs/getting-started/products/yvaults/vault-factory.md
> +**StrategyConvexFactory** supplies any additional Curve LP tokens (beyond which can receive the maximumum 2.5x boost via the Curve strategy) to Convex Finance to earn CRV rewards (boosted by Convex's
maximumum > maximum

2023-01-03 22:45 UTC, DarkGhost7 commented on docs/getting-started/products/yvaults/vault-factory.md
> +The first Vault Factory deployed live on Ethereum is the Curve LP Token Vault Factory. This factory allows users to deploy yVaults for any Curve LP token that represents a Curve pool with an active g
receiving > receive

2023-01-03 22:45 UTC, DarkGhost7 commented on docs/getting-started/products/yvaults/vault-factory.md
> +Performance fees for every type of yVault go straight to yearn treasury ([ychad.eth](https://etherscan.io/address/0xfeb4acf3df3cdea7399794d0869ef76a6efaff52)) and are calculated only on top of harves
Yearn

2023-01-03 22:45 UTC, DarkGhost7 commented on docs/getting-started/products/yvaults/vault-factory.md
> +2. Call `createNewVaultsAndStrategies()` to create a new permisionless vault for.
delete `for`

2023-01-03 23:41 UTC, DarkGhost7 approved these changes
lgtm

2023-01-05 16:40 UTC, saltyfacu approved these changes
great job here

2023-01-05 16:40 UTC, merged